import { HeroSlide, ProductItem, StatItem } from "./types";

export const heroSlides: HeroSlide[] = [
  {
    id: 1,
    modelCode: "AM-POD-X1",
    badge: "Smart Digital Podium",
    image: "/images/product-podium-cutout.png",
    productCutout: "/images/product-podium-cutout.png",
    eyebrow: "INTELLIGENT PRESENTATION HARDWARE",
    title: "SMART DIGITAL",
    subtitle: "PODIUM & LECTERN",
    highlight: "Apex Series",
    tagline: "Dual Gooseneck Audio • Front Dynamic Display",
    screenSize: '21.5" Multi-Touch',
    description:
      "An all-in-one presentation solution featuring a 10-point multi-touch display, high-performance Wi-Fi PC, integrated PA system, visualizer workspace, multiple connectivity ports, and a sleek ultra-slim metal design. With a 32 inches optional front display, movable locking wheels, and customizable configurations, it delivers a seamless and professional presentation experience.",
    category: "Digital Podium",
    categoryNumber: "01",
    accentColor: "#FF2B35",
    accentGlow: "rgba(255, 43, 53, 0.45)",
    specs: [
      { label: "Main Touch", value: '21.5" FHD IPS PCAP' },
      { label: "Front Display", value: "LED Dynamic Graphic" },
      { label: "Microphones", value: "Dual XLR Gooseneck" },
      { label: "Enclosure", value: "Aero Aluminum & Steel" },
    ],
    features: [
      "Dual Shock-Mounted Gooseneck Mics",
      "Real-Time Annotation & Touch Matrix",
      "Secondary Audience Feed Output",
      "Integrated Crestron / Extron Control",
    ],
  },
  {
    id: 2,
    modelCode: "AM-KSK-24P",
    badge: "Self-Service Ordering",
    image: "/images/product-kiosk-cutout.png",
    productCutout: "/images/product-kiosk-cutout.png",
    eyebrow: "COMMERCIAL RETAIL & HOSPITALITY",
    title: "SELF-SERVICE",
    subtitle: "ORDER & PAY KIOSK",
    highlight: "QuickPay Station",
    tagline: "Touch Ordering • POS Terminal • Thermal Print",
    screenSize: '24"–32" PCAP Display',
    description:
      "Perfectly designed for interactive engagement, our Angled Touch Kiosk offers a smooth touch experience, ideal for information access, navigation, and customer interaction in any environment.",
    category: "Order Kiosk",
    categoryNumber: "02",
    accentColor: "#F59E0B",
    accentGlow: "rgba(245, 158, 11, 0.45)",
    specs: [
      { label: "Touch Screen", value: '24" Full HD PCAP Touch' },
      { label: "POS Payment", value: "EMV & Contactless Mount" },
      { label: "Printer", value: "80mm Thermal Receipt" },
      { label: "Scanner", value: "1D/2D QR & Barcode" },
    ],
    features: [
      "Sub-5ms Ultra-Responsive Touch",
      "PCI-PTS Certified POS Bracket",
      "ADA Compliant Ergonomic Stand",
      "Industrial 24/7 Thermal Cooling",
    ],
  },
  {
    id: 3,
    modelCode: "AM-SGN-32S",
    badge: "Commercial Advertising",
    image: "/images/product-signage-cutout.png",
    productCutout: "/images/product-signage-cutout.png",
    eyebrow: "DIGITAL SIGNAGE & BRANDING",
    title: "SLIM DIGITAL",
    subtitle: "Standee",
    highlight: "32\" SlimSign Totem",
    tagline: "Ultra-Thin Profile • 24/7 Commercial Duty",
    screenSize: '32" 4K/FHD High-Bright',
    description:
      "Ultra-thin freestanding commercial digital signage display totem on a heavy-duty weighted steel pedestal. Designed for luxury retail boutiques, corporate lobbies, hotel receptions, and digital advertising.",
    category: "Digital Standee",
    categoryNumber: "03",
    accentColor: "#00A3FF",
    accentGlow: "rgba(0, 163, 255, 0.45)",
    specs: [
      { label: "Panel Size", value: '32" Commercial IPS LED' },
      { label: "Brightness", value: "500+ Nits Anti-Glare" },
      { label: "Pedestal", value: "Heavy Solid Steel Base" },
      { label: "OS Support", value: "Android / Windows OPS" },
    ],
    features: [
      "Razor-Thin Edge-to-Edge Bezel",
      "24/7 Continuous Operation Rating",
      "Cloud CMS Remote Management",
      "Concealed Hidden Cable Routing",
    ],
  },
  {
    id: 4,
    modelCode: "AM-WAY-55D",
    badge: "Architectural Wayfinding",
    image: "/images/product-wayfinding-cutout.png",
    productCutout: "/images/product-wayfinding-cutout.png",
    eyebrow: "ENTERPRISE MALL & AIRPORT DIRECTORY",
    title: "Digital ",
    subtitle: "Wayfinding Kiosk",
    highlight: "K-Select Dual Pillar",
    tagline: "Dual-Pillar Design • 3D Interactive Maps",
    screenSize: '55" Ultra-Clear Multi-Touch',
    description:
      "Sculptural dual-pillar interactive wayfinding and directory kiosk for premium shopping malls, corporate campuses, and transit hubs. Features perforated backlit floor indicators and multi-touch 3D navigation.",
    category: "Wayfinding Kiosk",
    categoryNumber: "04",
    accentColor: "#10B981",
    accentGlow: "rgba(16, 185, 129, 0.45)",
    specs: [
      { label: "Main Screen", value: '55" 4K UHD Multi-Touch' },
      { label: "Floor Guide", value: "Perforated LED Backlit" },
      { label: "Enclosure", value: "Sculptural Poly-Steel" },
      { label: "Protection", value: "IK08 Laminated Glass" },
    ],
    features: [
      "Interactive 3D Multi-Floor Maps",
      "Dual-Pillar Integrated Pillar Guide",
      "Smart Multi-Tenant Directory Search",
      "High-Traffic Vandal-Resistant Body",
    ],
  },
  {
    id: 5,
    modelCode: "AM-TC-43H",
    badge: "Interactive Info Console",
    image: "/images/product-console-cutout.png",
    productCutout: "/images/product-console-cutout.png",
    eyebrow: "CORPORATE LOBBY & EXHIBITION CENTERS",
    title: "SLANTED TOUCH",
    subtitle: "INFORMATION KIOSK",
    highlight: "Horizon Pedestal",
    tagline: "45° Ergonomic Angle • E-Directory Stand",
    screenSize: '32"–43" Widescreen Touch',
    description:
      "Ergonomically tilted multi-touch information station on a minimalist vertical column. Perfect for museum exhibits, hotel concierge desks, real estate virtual tours, and visitor check-ins.",
    category: "Slanted Kiosk",
    categoryNumber: "05",
    accentColor: "#8B5CF6",
    accentGlow: "rgba(139, 92, 246, 0.45)",
    specs: [
      { label: "Tilt Angle", value: "45° Ergonomic Slant" },
      { label: "Screen Glass", value: "Anti-Glare Gorilla Glass" },
      { label: "Pedestal", value: "Matte Black Steel Column" },
      { label: "Response", value: "Sub-5ms Touch Latency" },
    ],
    features: [
      "Comfortable Standing Touch Angle",
      "Ultra-Fast Multi-Finger Tracking",
      "Anti-Fingerprint Oleophobic Coating",
      "Solid Balanced Steel Floor Base",
    ],
  },
];

export const products: ProductItem[] = [
  {
    id: "podium",
    title: "Smart Digital Podium",
    category: "Digital Lecterns",
    badge: "Apex Series",
    description:
      "Make a bold statement with our Digital Standee. Its sleek vertical design is perfect for advertising, wayfinding, and engaging your audience in high-traffic areas.",
    image: "/images/product-podium-cutout.png",
    specs: ['21.5" FHD Touch', "Dual XLR Audio", "LED Front Panel", "Crestron Ready"],
    features: ["Digital Annotation", "Hidden Cable Routing", "Aero-Grade Aluminum"],
  },
  {
    id: "Touch kiosk",
    title: "Self-Service Order Kiosk",
    category: "Interactive POS",
    badge: "QuickPay",
    description:
      "Industrial-grade self-service ordering and payment kiosk with integrated thermal receipt printer, contactless POS terminal mount, and 2D barcode scanner.",
    image: "/images/product-kiosk-cutout.png",
    specs: ['24" FHD PCAP Touch', "POS Terminal Mount", "Thermal Printer", "2D Scanner"],
    features: ["Sub-5ms Response", "Tamper-Proof Lock", "ADA Compliant"],
  },
  {
    id: "Standees",
    title: "Slim Digital Signage",
    category: "Commercial Displays",
    badge: "32\" SlimSign",
    description:
      "Ultra-slim commercial floor-standing digital signage totem on heavy steel base. High-brightness 24/7 duty cycle for luxury retail and hotel receptions.",
    image: "/images/product-signage-cutout.png",
    specs: ['32" High-Bright LED', "500+ Nits Brightness", "Solid Steel Base", "Android / Windows"],
    features: ["Ultra-Slim Bezel", "24/7 Commercial Duty", "Cloud CMS"],
  },
  {
    id: "wayfinding",
    title: "Architectural Wayfinding Totem",
    category: "Mall & Campus Totems",
    badge: "K-Select",
    description:
      "Futuristic dual-pillar shopping mall directory totem with backlit LED floor guide and 55-inch 4K multi-touch interactive 3D wayfinding interface.",
    image: "/images/product-wayfinding-cutout.png",
    specs: ['55" 4K Multi-Touch', "LED Backlit Guide", "Poly-Steel Body", "IK08 Glass"],
    features: ["3D Floor Wayfinding", "Dual-Pillar Design", "Multi-Tenant Search"],
  },
  {
    id: "touch-console",
    title: "Slanted Touch Information Kiosk",
    category: "Lobby & Exhibition",
    badge: "Horizon",
    description:
      "Ergonomic 45-degree angled multi-touch information station on matte black pedestal for corporate lobby directories and interactive museum exhibits.",
    image: "/images/product-console-cutout.png",
    specs: ["45° Slanted Touch", "Anti-Glare Glass", "Matte Black Base", "Sub-5ms Latency"],
    features: ["Ergonomic Viewing", "Multi-Touch Accuracy", "Heavy Base Stand"],
  },
];


export const companyInfo = {
  name: "AMIACH Technologies",
  tagline: "Smart AV Hardware, Interactive Kiosks & Digital Podiums Manufacturing.",
  description:
    "AMIACH Technologies is a premier manufacturer of interactive digital podiums, self-service ordering kiosks, commercial digital signage displays, and architectural wayfinding totems built for enterprise excellence.",
  address: "STPI Shastripuram , Agra ",
  email: "about@amiach.tech",
  salesEmail: "about@amiach.tech",
  phone: "+91 989 725 8005",
  hours: "Monday – Friday: 8:00 AM – 6:00 PM PST",
  socials: {
    linkedin: "https://linkedin.com/company/amiach-technologies",
    instagram: "https://instagram.com/amiachtechnologies",
    facebook: "https://facebook.com/amiachtechnologies",
    twitter: "https://twitter.com/amiachtechnologies",
  },
};